# Generated by Django 2.2.13 on 2020-09-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_phonecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='validate_phone',
            field=models.BooleanField(default=False),
        ),
    ]
