# Generated by Django 2.2.13 on 2020-09-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_validate_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='validate_phone',
            new_name='validated_phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
