# Generated by Django 2.2.13 on 2020-09-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200913_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressuser',
            name='coords',
            field=models.CharField(default='none', max_length=300),
            preserve_default=False,
        ),
    ]
