# Generated by Django 2.2.13 on 2020-09-28 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_addressuser_coords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vehicle', models.IntegerField(default=0)),
                ('serie', models.CharField(max_length=10)),
                ('license_front', models.ImageField(upload_to='license_front')),
                ('license_back', models.ImageField(upload_to='license_back')),
                ('document_vehicle_1', models.ImageField(upload_to='document_vehicle_1')),
                ('document_vehicle_2', models.ImageField(upload_to='document_vehicle_2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
