# Generated by Django 2.2.13 on 2020-10-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecode',
            name='type_code',
            field=models.IntegerField(default=0),
        ),
    ]
