# Generated by Django 2.2.13 on 2020-10-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_phonecode_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
