# Generated by Django 2.2.13 on 2020-10-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_vehicle_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonecode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model_vehicle',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
