# Generated by Django 2.2.13 on 2020-10-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201031_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecode',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='antecedentes_back',
            field=models.ImageField(blank=True, upload_to='antecedentes_back'),
        ),
        migrations.AddField(
            model_name='user',
            name='antecedentes_front',
            field=models.ImageField(blank=True, upload_to='antecedentes_front'),
        ),
    ]
