# Generated by Django 2.2.13 on 2020-11-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201031_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressuser',
            name='coords',
        ),
        migrations.AddField(
            model_name='addressuser',
            name='lat',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='addressuser',
            name='lng',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
