# Generated by Django 2.2.13 on 2021-01-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201119_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driver_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addressuser',
            name='notes',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='user',
            name='antecedentes_back',
            field=models.ImageField(blank=True, null=True, upload_to='antecedentes_back'),
        ),
        migrations.AlterField(
            model_name='user',
            name='antecedentes_front',
            field=models.ImageField(blank=True, null=True, upload_to='antecedentes_front'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='document_vehicle_1',
            field=models.ImageField(null=True, upload_to='document_vehicle_1'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='document_vehicle_2',
            field=models.ImageField(null=True, upload_to='document_vehicle_2'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_back',
            field=models.ImageField(null=True, upload_to='license_back'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_front',
            field=models.ImageField(null=True, upload_to='license_front'),
        ),
    ]
