# Generated by Django 2.2.13 on 2020-10-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_order_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
