# Generated by Django 2.2.13 on 2020-10-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_auto_20201001_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionshop',
            name='title',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
