# Generated by Django 2.2.13 on 2020-10-02 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_promotionshop_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryshop',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='experienceshop',
            name='shop',
        ),
        migrations.AddField(
            model_name='categoryshop',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='directory.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experienceshop',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='directory.Product'),
            preserve_default=False,
        ),
    ]
