# Generated by Django 2.2.13 on 2020-10-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_auto_20201002_1126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryShop',
            new_name='CategoryProduct',
        ),
        migrations.RenameModel(
            old_name='ExperienceShop',
            new_name='ExperienceProduct',
        ),
    ]
