# Generated by Django 2.2.13 on 2020-10-03 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_auto_20201002_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_to_delivery',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_delivery', to=settings.AUTH_USER_MODEL),
        ),
    ]
