# Generated by Django 2.2.13 on 2020-10-03 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_auto_20201003_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.AddressUser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_to_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
