# Generated by Django 2.2.13 on 2020-11-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_auto_20201003_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='lat',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='shop',
            name='lng',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
