# Generated by Django 2.2.13 on 2020-11-30 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_auto_20201119_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistoryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Order')),
            ],
        ),
    ]
