# Generated by Django 2.2.13 on 2020-11-30 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_orderhistorystatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='code',
        ),
    ]
