# Generated by Django 2.2.13 on 2021-03-02 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0014_auto_20210122_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataGPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=300)),
                ('lng', models.CharField(max_length=300)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='directory.CategoryGroup'),
            preserve_default=False,
        ),
    ]
