# Generated by Django 2.2.13 on 2021-03-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0015_auto_20210302_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type_product',
        ),
    ]
