# Generated by Django 2.2.13 on 2021-03-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0019_usershop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
