# Generated by Django 2.2.13 on 2021-04-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0021_auto_20210330_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='hours_sat_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='hours_sat_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='hours_sun_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='hours_sun_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='hours_week_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='hours_week_start',
            field=models.IntegerField(default=0),
        ),
    ]
