# Generated by Django 2.2.13 on 2021-04-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0022_auto_20210401_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cooking_time',
            field=models.IntegerField(default=0),
        ),
    ]
