# Generated by Django 2.2.13 on 2021-04-06 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0023_order_cooking_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Shop')),
            ],
        ),
    ]
